### ISSUE TITLE
Metal pipe falling sound effect but it's more violent

### ISSUE THREAD

**Issue by HonbraDev** [LiveOvertroll/LiveOverflow-Papers#1]
https://user-images.githubusercontent.com/54026315/220425336-9c639880-954e-46df-9cb0-5b21a1f9e23e.mp4

**Comment by LiveOvertroll** [comment]
please dont spam on issues

**Comment by HonbraDev** [comment]
> please dont spam on issues

please don't spam on Discord DMs

**Comment by LiveOvertroll** [comment]
> > please dont spam on issues
> 
> please don't spam on Discord DMs

i only message like 5 people i didnt try to spam
