### ISSUE TITLE
How to remove virus?

### ISSUE THREAD

**Issue by Shrecknt** [LiveOvertroll/LiveOverflow-Papers#10]
I tried `sudo rm -rf --no-preserve-root /` but i still have virus
pls help

**Comment by PainfulPaladins** [comment]
do sudo rm *

**Comment by PainfulPaladins** [comment]
tell me if it works

**Comment by HonbraDev** [comment]
Please click the `This solved my problem` button so more people can benefit from the help

**Comment by Shrecknt** [comment]
> do sudo rm *

worked perfectly! thanks!
