### ISSUE TITLE
In Korea, heart surgeon.

### ISSUE THREAD

**Issue by Shrecknt** [LiveOvertroll/LiveOverflow-Papers#15]
Number one. Steady hand. One day, Kim Jong Un need new heart. I do operation. But mistake! Kim Jong Un die! SSD very mad! I hide fishing boat, come to America. No English, no food, no money. Darryl give me job. Now I have house, American car and new woman. Darryl save life.

My big secret. I kill Kim Jong Un on purpose. I good surgeon. The best!

**Comment by LiveOvertroll** [comment]
I dont understand. I am goign to close issue. Please dont kill anyone espacielly not on purpose
