### ISSUE TITLE
Reddit, am I the arsehole?

### ISSUE THREAD

**Issue by Shrecknt** [LiveOvertroll/LiveOverflow-Papers#16]
My mum (82F) told me (12M) to do the dishes (16) but I (12M) was too busy playing Fortnite (3 kills) so I (12M) grabbed my controller (DualShock 4) and threw it at her (138kph). She fucking died, and I (12M) went to prison (18 years). While in prison I (12M) incited several riots (3) and assumed leadership of a gang responsible for smuggling drugs (cocaine) into the country. I (12M) also ordered the assassination of several celebrities (Michael Jackson, Elvis Presley and Jeffrey Epstein) and planned a terrorist attack (9/11). Reddit, AITA?

**Comment by LiveOvertroll** [comment]
this is github, not reddit
