### ISSUE TITLE
AITA for not showing up to my own funeral?

### ISSUE THREAD

**Issue by Shrecknt** [LiveOvertroll/LiveOverflow-Papers#19]
So I (74M) was recently hit by a car (2014 Honda) and died. My wife (5F) organized me a funeral (cost $2747) without asking me (74M) at all. I (74M) was unable to make it because I (74M) was dead (17 days). At the funeral I heard my dad (15M) and other family members talking about how they wish I could be there and now I feel bad for not showing up. AITA?

**Comment by LiveOvertroll** [comment]
i dont even understand anymore
