### ISSUE TITLE
I did sudo rm *

### ISSUE THREAD

**Issue by oriyadid** [LiveOvertroll/LiveOverflow-Papers#23]
do sudo rm *

_Originally posted by @PainfulPaladins in https://github.com/LiveOvertroll/LiveOverflow-Papers/issues/10#issuecomment-1438935695_

**Comment by PainfulPaladins** [comment]
it worked, right?

**Comment by oriyadid** [comment]
My computer refuses to start now, please help
I am posting this from my Samsung Family Hub Plus Quad Door Smart Refrigerator™

**Comment by PainfulPaladins** [comment]
but it removed virus right?

**Comment by Windowsk** [comment]
Peasant.

Sent from my Honda Smart Rock

**Comment by oriyadid** [comment]
> but it removed virus right?

Yeah it did, but it also removed not virus
# **PLEASE HELP ME**

**Comment by PainfulPaladins** [comment]
uh i dont know that much, sorry

**Comment by oriyadid** [comment]
oh
well that sucks

**Comment by LiveOvertroll** [comment]
i cant do a lot of linux but i think this removes all you have on your computer. please dont do that
