### ISSUE TITLE
So my kid is a furry

### ISSUE THREAD

**Issue by Windowsk** [LiveOvertroll/LiveOverflow-Papers#27]
My middle daughter is 14. She has told her sister that she identifies as a furry. I’m not even quite sure what all that means. When I asked her about it, she said it’s someone who wears an animal costume. My husband told her absolutely no way you can be a male or you can be a female, but you’re not going to be an animal or a toaster or an inanimate object. I guess my question is what exactly is a furry? And what, as a parent, should I be doing, saying, encouraging, discouraging? I think in general she is trying to find her self. I try to be open and encouraging and excepting of her. I know that she has a lot of friends that are all over the gender identity, scale, spectrum or whatever and pan, friends, trans, friends, etc. and is very supportive of all of them. And I’ve asked her if she likes girls or boys or it identifies as any of those things and she says no and I reinforce that I just want her to be happy whatever it is. But a furry? I don’t know how to get on board with that. I also realize that just because I’m unaware of something or uncomfortable with something it doesn’t make it wrong. It just makes it different. However, this is so far out of my comfort zone zone. So if you guys could be kind to this nearly 50 year old mom who is trying to figure out life with the younger kids in today’s world, I would appreciate any insight .

**Comment by LiveOvertroll** [comment]
i hate furries and why do you have this copy pastea
