### ISSUE TITLE
anybody wanna play chess? 1. e4

### ISSUE THREAD

**Issue by PainfulPaladins** [LiveOvertroll/LiveOverflow-Papers#29]

**Comment by oriyadid** [comment]
e5

**Comment by Windowsk** [comment]
no

**Comment by oriyadid** [comment]
> no

rude D:

**Comment by PainfulPaladins** [comment]
1. e4 e5 2. Nf3

**Comment by Windowsk** [comment]
> > no
> 
> rude D:

I was just answering the question

**Comment by oriyadid** [comment]
Nc6

> 1. e4 e5 2. Nf3

**Comment by PainfulPaladins** [comment]
1. e4 e5 2. Nf3 Nc6 3. Nc3

**Comment by oriyadid** [comment]
Bc5

thanks for keeping the moves organised

**Comment by PainfulPaladins** [comment]
1. e4 e5 2. Nf3 Nc6 3. Nc3 Bc5 4. Bc4

**Comment by oriyadid** [comment]
Nf6

copycat variation :D

**Comment by PainfulPaladins** [comment]
1. e4 e5 2. Nf3 Nc6 3. Nc3 Bc5 4. Bc4 Nf6 5. O-O

**Comment by oriyadid** [comment]
d6

**Comment by PainfulPaladins** [comment]
1. e4 e5 2. Nf3 Nc6 3. Nc3 Bc5 4. Bc4 Nf6 5. O-O d6 6. Ng5

**Comment by oriyadid** [comment]
O-O

**Comment by PainfulPaladins** [comment]
1. e4 e5 2. Nf3 Nc6 3. Nc3 Bc5 4. Bc4 Nf6 5. O-O d6 6. Ng5 O-O 7. Bd5

**Comment by oriyadid** [comment]
Bg4

I'll be back soon, enjoy this while I am gone

![Plateau cta](https://user-images.githubusercontent.com/60009101/220442422-a0aa96cb-42ca-4cac-8104-9820ac5facec.jpg)

**Comment by PainfulPaladins** [comment]
ok!

**Comment by Shrecknt** [comment]
How clever, the schizimbibblewozzle gambit!

**Comment by oriyadid** [comment]
Still not back, but swp wanted to contribute to the conversation
![](https://media.tenor.com/CPEZLXBt4UAAAAAC/bobbychess-chess.gif)

edit: fixed link

**Comment by PainfulPaladins** [comment]
1. e4 e5 2. Nf3 Nc6 3. Nc3 Bc5 4. Bc4 Nf6 5. O-O d6 6. Ng5 O-O 7. Bd5 Bg4 i think you are using stockfish but who cares, man vs machine

**Comment by PainfulPaladins** [comment]
1. e4 e5 2. Nf3 Nc6 3. Nc3 Bc5 4. Bc4 Nf6 5. O-O d6 6. Ng5 O-O 7. Bd5 Bg4 8. Nf3

**Comment by oriyadid** [comment]
Issues are beginning to close
Farewell, my friend
 
> i think you are using stockfish but who cares, man vs machine

I haven't considered using stockfish until shrecknt mentioned it, so far this is stuff I've seen before

**Comment by PainfulPaladins** [comment]
goodbye

**Comment by HonbraDev** [comment]
`o>`

**Comment by LiveOvertroll** [comment]
>Issues are beginning to close
>Farewell, my friend

ok it is nice that you have chess game here, i wont close it, but please dont spam too much
try doing it somewhere else

**Comment by PainfulPaladins** [comment]
oh lol

> Issues are beginning to close Farewell, my friend
> 
> > i think you are using stockfish but who cares, man vs machine
> 
> I haven't considered using stockfish until shrecknt mentioned it, so far this is stuff I've seen before

lol

**Comment by PainfulPaladins** [comment]
@RealY700 whats your dis

**Comment by PainfulPaladins** [comment]
i wanna finish this

**Comment by oriyadid** [comment]
> @RealY700 whats your dis

RealY700#7434, just messaged you

**Comment by oriyadid** [comment]
> > Issues are beginning to close
> > Farewell, my friend
> 
> ok it is nice that you have chess game here, i wont close it, but please dont spam too much try doing it somewhere else

We are doing it on discord, feel free to close it now
