### ISSUE TITLE
Ruining the challenge

### ISSUE THREAD

**Issue by ActuallyRuben** [LiveOvertroll/LiveOverflow-Papers#33]
As you might've noticed, people aren't happy with you leaking this info. I personally see finding the address as a challenge with access to the server as a reward. Aside from that, just giving away the answer to a challenge you solved is plain boring.

Can you perhaps explain your reasoning for doing this?

**Comment by ActuallyRuben** [comment]
Could you answer the question, perhaps?

**Comment by LiveOvertroll** [comment]
no

**Comment by ActuallyRuben** [comment]
yes

**Comment by HonbraDev** [comment]
> no

understandable, have a bad day
