### ISSUE TITLE
jink

### ISSUE THREAD

**Issue by veronoicc** [LiveOvertroll/LiveOverflow-Papers#34]
https://user-images.githubusercontent.com/64193056/220839118-cf0bb165-748f-4b92-9ace-ff15f49b44de.mp4

https://user-images.githubusercontent.com/64193056/220839382-0be067de-75fa-4bb9-9d8e-04b79f1832ba.mp4

https://user-images.githubusercontent.com/64193056/220839876-a59e4487-d051-44aa-95eb-0fc0fb9d921f.mp4

https://user-images.githubusercontent.com/64193056/220840186-4905f046-333c-422c-a1c7-845fef39fa4f.mp4

https://user-images.githubusercontent.com/64193056/220841152-df30a6ad-0019-4945-9f61-955493afccaf.mp4

https://user-images.githubusercontent.com/64193056/220839131-c2bd5b1e-bb4c-4012-ac65-b2dd70f13220.mp4

https://user-images.githubusercontent.com/64193056/220839155-26835a3f-1d6e-48e9-bb46-0a4549368a95.mp4

https://user-images.githubusercontent.com/64193056/220839177-29744307-54d3-4802-90b8-e9705b6b5d53.mp4

**Comment by LiveOvertroll** [comment]
is that your cat?

**Comment by LiveOvertroll** [comment]
i am closing

**Comment by HonbraDev** [comment]
> is that your cat?

no but this is

![my cat](https://user-images.githubusercontent.com/54026315/221004347-06446536-1b7a-4be5-8c7e-9587b98fc81f.png)

**Comment by veronoicc** [comment]
It's not my cat, but at least it's cute enough to keep the issue open no? @LiveOvertroll

**Comment by veronoicc** [comment]
Also why did you close this as completed? I have far more images/videos of jinx i need to upload, so this is by far not completed.
