### ISSUE TITLE
how to installs minecraft?

### ISSUE THREAD

**Issue by DesiCow** [LiveOvertroll/LiveOverflow-Papers#38]
I selled my wife for internet connection and minecraft account, but now I cannot install minecraft? I am using TempleOS and when I go to download page there is only mac linux and windows??? What are these things? My brother from india tells me they are useless things no person of god should use. How can I install minecraft on my computer of god?

**Comment by LiveOvertroll** [comment]
i dont know if this is real or copy pastea now
